name: Lista Lending
icon: logo.png
category: Money Market
url: https://lista.org/lending
description: Redefining BNB with Liquid Staking, Lista Lending and CDP Solutions
metadata:
  pt:
    - chainId: 56
      address: '0x54a8f370575fe98c305640d7d11b8aa2df451b13'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0xa44adcc94ded8fe976419e3ebb4fe149b9cdec4893e870eecb46541b11099268
      description: >-
        PT-reUSD-25JUN2026 can be used as collateral to borrow or multiply
        against USDT
      subtitle: USDT
  yt: []
  lp: []
