name: Lista Lending
icon: logo.png
category: Money Market
url: https://lista.org/lending
description: Redefining BNB with Liquid Staking, Lista Lending and CDP Solutions
metadata:
  pt: []
  yt: []
  lp: []
