name: Euler
icon: logo.png
category: Money Market
url: https://app.euler.finance/borrow?network=ethereum
description: >-
  Euler is a modular lending platform that enables users to lend, borrow and
  build without limits.
metadata:
  pt:
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x9dfe82d2a2419b143d99a36789c405f2d8072c1e/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in an Euler
        market with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDe
      relatedAsset: '0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6'
      integrationUrl: >-
        https://app.euler.finance/positions/0x9dfe82d2a2419b143d99a36789c405f2d8072c1e/0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6?network=ethereum
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in an Euler
        market with eUSDe-6 as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: eUSDe
      relatedAsset: '0x61aac438453d6e3513c0c8dbb69f13860e2b5028'
      integrationUrl: >-
        https://app.euler.finance/positions/0x9dfe82d2a2419b143d99a36789c405f2d8072c1e/0x61aac438453d6e3513c0c8dbb69f13860e2b5028?network=ethereum
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in an Euler
        market with eeUSDe-1 as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0xd5f9afc441ca3f72b22d0b60d53e55b966c8de64/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in an Euler market
        with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDe
      relatedAsset: '0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6'
      integrationUrl: >-
        https://app.euler.finance/positions/0xd5f9afc441ca3f72b22d0b60d53e55b966c8de64/0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6?network=ethereum
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in an Euler market
        with eUSDe-6 as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: eUSDe
      relatedAsset: '0x61aac438453d6e3513c0c8dbb69f13860e2b5028'
      integrationUrl: >-
        https://app.euler.finance/positions/0xd5f9afc441ca3f72b22d0b60d53e55b966c8de64/0x61aac438453d6e3513c0c8dbb69f13860e2b5028?network=ethereum
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in an Euler market
        with eeUSDe-1 as the loan token.
    - chainId: 1
      address: '0x5b1578e2604b91bd7b24f86f0e5ef6c024bb3a14'
      subtitle: hgETH
      relatedAsset: '0x3f714090f7648139043349f599a48904187d76d0'
      integrationUrl: >-
        https://app.euler.finance/positions/0x18337806b02b02099209b05589e6db85acd4345c/0x3f714090f7648139043349f599a48904187d76d0?network=ethereum
      description: >-
        The PT-hgETH-25JUN2026 is the asset used as collateral in an Euler
        market with ehgETH-2 as the loan token.
    - chainId: 1
      address: '0x5b1578e2604b91bd7b24f86f0e5ef6c024bb3a14'
      subtitle: WETH
      relatedAsset: '0x87c414825ab3d1e9bdc773e9b1fd968822c9cf51'
      integrationUrl: >-
        https://app.euler.finance/positions/0x18337806b02b02099209b05589e6db85acd4345c/0x87c414825ab3d1e9bdc773e9b1fd968822c9cf51?network=ethereum
      description: >-
        The PT-hgETH-25JUN2026 is the asset used as collateral in an Euler
        market with eWETH-29 as the loan token.
    - chainId: 42161
      address: '0xe46271ecb1d5c7c5134868760f10c18b03021ef1'
      subtitle: USDC
      relatedAsset: '0x44c10da836d2abe881b77bbb0b3dce5f85c0c1cc'
      integrationUrl: >-
        https://app.euler.finance/positions/0x27b3b7f97ef233912384d0b5b3844173710f4d3c/0x44c10da836d2abe881b77bbb0b3dce5f85c0c1cc?network=arbitrumone
      description: >-
        The PT-thBILL-18JUN2026 is the asset used as collateral in an Euler
        market with eUSDC-6 as the loan token.
    - chainId: 42161
      address: '0xe46271ecb1d5c7c5134868760f10c18b03021ef1'
      subtitle: thBILL
      relatedAsset: '0x79e1f4a1cde92568d58eb823f81d9c0c7c384e6b'
      integrationUrl: >-
        https://app.euler.finance/positions/0x27b3b7f97ef233912384d0b5b3844173710f4d3c/0x79e1f4a1cde92568d58eb823f81d9c0c7c384e6b?network=arbitrumone
      description: >-
        The PT-thBILL-18JUN2026 is the asset used as collateral in an Euler
        market with ethBILL-2 as the loan token.
    - chainId: 42161
      address: '0xe46271ecb1d5c7c5134868760f10c18b03021ef1'
      subtitle: USD₮0
      relatedAsset: '0xee074ceb44ada094391b9c71a7fb8ba6962d492c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x27b3b7f97ef233912384d0b5b3844173710f4d3c/0xee074ceb44ada094391b9c71a7fb8ba6962d492c?network=arbitrumone
      description: >-
        The PT-thBILL-18JUN2026 is the asset used as collateral in an Euler
        market with eUSD₮0-5 as the loan token.
  sy: []
  lp: []
