name: Contango
icon: logo.png
category: Yield Strategy
url: https://app.contango.xyz/
description: >-
  Contango builds positions by automating looping strategies through flash
  loans. When a trader opens a position, the protocol borrows on money markets.
metadata:
  pt:
    - chainId: 1
      address: '0x5b1578e2604b91bd7b24f86f0e5ef6c024bb3a14'
      integrationUrl: >-
        https://app.contango.xyz/strategies/leveraged-staking/eth?selectedChains=1
      description: PT leverage looping through various supported money markets
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      integrationUrl: https://app.contango.xyz/
      description: PT leverage looping through various supported money markets
    - chainId: 1
      address: '0x3eaa0f0f0a5d3d595ae4e4b0d27f439d01c3e7b2'
      integrationUrl: https://app.contango.xyz/
      description: PT leverage looping through various supported money markets
  yt: []
  lp: []
