name: Aave
icon: logo.png
category: Money Market
description: >-
  Aave is a decentralised non-custodial liquidity protocol where users can
  participate as suppliers or borrowers
url: https://app.aave.com/
metadata:
  pt:
    - chainId: 1
      address: '0x9db38d74a0d29380899ad354121dfb521adb0548'
      subtitle: USDC
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x9db38d74a0d29380899ad354121dfb521adb0548&marketName=proto_ethereum_v3
      description: PT-USDG-28MAY2026 can be used as collateral to borrow USDC on Aave
    - chainId: 1
      address: '0x9db38d74a0d29380899ad354121dfb521adb0548'
      subtitle: USDT
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x9db38d74a0d29380899ad354121dfb521adb0548&marketName=proto_ethereum_v3
      description: PT-USDG-28MAY2026 can be used as collateral to borrow USDT on Aave
    - chainId: 1
      address: '0x9db38d74a0d29380899ad354121dfb521adb0548'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x9db38d74a0d29380899ad354121dfb521adb0548&marketName=proto_ethereum_v3
      description: PT-USDG-28MAY2026 can be used as collateral to borrow USDe on Aave
    - chainId: 1
      address: '0x9db38d74a0d29380899ad354121dfb521adb0548'
      subtitle: USDG
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x9db38d74a0d29380899ad354121dfb521adb0548&marketName=proto_ethereum_v3
      description: PT-USDG-28MAY2026 can be used as collateral to borrow USDG on Aave
    - chainId: 9745
      address: '0x30559e3d35e33ab69399a3fe9f383d32bd3c016e'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x30559e3d35e33ab69399a3fe9f383d32bd3c016e&marketName=proto_plasma_v3
      description: PT-sUSDE-18JUN2026 can be used as collateral to borrow USDe on Aave
    - chainId: 9745
      address: '0x30559e3d35e33ab69399a3fe9f383d32bd3c016e'
      subtitle: USDT0
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x30559e3d35e33ab69399a3fe9f383d32bd3c016e&marketName=proto_plasma_v3
      description: PT-sUSDE-18JUN2026 can be used as collateral to borrow USDT0 on Aave
    - chainId: 9745
      address: '0x30559e3d35e33ab69399a3fe9f383d32bd3c016e'
      subtitle: GHO
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x30559e3d35e33ab69399a3fe9f383d32bd3c016e&marketName=proto_plasma_v3
      description: PT-sUSDE-18JUN2026 can be used as collateral to borrow GHO on Aave
    - chainId: 9745
      address: '0x23b17d3944742ace3d0c71586fcb320d1e4a1ed2'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x23b17d3944742ace3d0c71586fcb320d1e4a1ed2&marketName=proto_plasma_v3
      description: PT-USDe-18JUN2026 can be used as collateral to borrow USDe on Aave
    - chainId: 9745
      address: '0x23b17d3944742ace3d0c71586fcb320d1e4a1ed2'
      subtitle: USDT0
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x23b17d3944742ace3d0c71586fcb320d1e4a1ed2&marketName=proto_plasma_v3
      description: PT-USDe-18JUN2026 can be used as collateral to borrow USDT0 on Aave
    - chainId: 9745
      address: '0x23b17d3944742ace3d0c71586fcb320d1e4a1ed2'
      subtitle: GHO
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x23b17d3944742ace3d0c71586fcb320d1e4a1ed2&marketName=proto_plasma_v3
      description: PT-USDe-18JUN2026 can be used as collateral to borrow GHO on Aave
    - chainId: 1
      address: '0x619d75e3b790ebc21c289f2805bb7177a7d732e2'
      subtitle: USDC
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x619d75e3b790ebc21c289f2805bb7177a7d732e2&marketName=proto_ethereum_v3
      description: PT-srUSDe-25JUN2026 can be used as collateral to borrow USDC on Aave
    - chainId: 1
      address: '0x619d75e3b790ebc21c289f2805bb7177a7d732e2'
      subtitle: USDT
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x619d75e3b790ebc21c289f2805bb7177a7d732e2&marketName=proto_ethereum_v3
      description: PT-srUSDe-25JUN2026 can be used as collateral to borrow USDT on Aave
    - chainId: 1
      address: '0x619d75e3b790ebc21c289f2805bb7177a7d732e2'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x619d75e3b790ebc21c289f2805bb7177a7d732e2&marketName=proto_ethereum_v3
      description: PT-srUSDe-25JUN2026 can be used as collateral to borrow USDe on Aave
  yt: []
  lp: []
