name: Morpho
icon: logo.png
category: Money Market
url: https://app.morpho.org/ethereum/borrow
description: >-
  A permissionless and non-custodial lending protocol where users can earn
  interest on over-collaterized lending and borrow digital assets using
  immutable infrastructure.
metadata:
  pt:
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x702b7ec7628de2622e51e1bb34a7e6ad9e95f3a25a2ed361e4ce621f23f5e642
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xfd039edc69eac5eaab4a10463fdbcaca75d6eddb1f0e00248d73fc977fb2554b
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 1
      address: '0xcc16cd49194e7aa3dca780c742580e2f9b418874'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xf80a664057fe3cadcd9e83f27bb1effe5c15d1d2648acc7634daff1581951b5e
      description: >-
        The PT-avUSD-14MAY2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x92a6a01b07984de46c24e8eba248449beb8b1dcb'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xed05fcc2893b78b3fa468d21b6e4d2925e7f2c64eb1f16279757c43f87502a99
      description: >-
        The PT-apxUSD-18JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x92a6a01b07984de46c24e8eba248449beb8b1dcb'
      subtitle: apxUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xf3814af4869a6ce59ffef016e555dd4c1e92bf383b5ab89abe496044c6364746
      description: >-
        The PT-apxUSD-18JUN2026 is the asset used as collateral in a Morpho
        market with apxUSD as the loan token.
    - chainId: 1
      address: '0x606b5c773dc4d6e625c411cf60565f8c30c467d2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xc978f01522ff64adafd91856065d602c56e326a0368b895bd9244d5998e60076
      description: >-
        The PT-savUSD-14MAY2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x82b853db31f025858792d8fa969f2a1dc245c179'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xc2bc5e1e304fb1ea103dcbee37ece3c7e9219fb4b2b19d8ffdf81c39f4fbf180
      description: >-
        The PT-srNUSD-28MAY2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x6c65db1d88c8eda1e3debf2b2ef3d0ece8600466'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xb62aac664f81d19f21a158aa0373967ef60fd1ac8de4a9091bd225c007973ca6
      description: >-
        The PT-sNUSD-4JUN2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 8453
      address: '0xc31e19dc6c8a90d628432e15bbd538aa8c789e5d'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/base/market/0xaf2657ed859dcac494afc20ba83e26fa153414da971a1f082ebfcb45d73955f1
      description: >-
        The PT-USDai-18JUN2026-(ARB) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x3365554a61ceff74a76528f9e86c1e87946d16a5'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xa75bb490ecfee90c86a9d22ebc2dde42fb83478b3f18722b9fc6f5f668cab124
      description: >-
        The PT-apyUSD-18JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x3365554a61ceff74a76528f9e86c1e87946d16a5'
      subtitle: apxUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x04663e98d677d8ef38b76d5a19d1fddc1aff10a86b71dc7f01cd8f5a18a16f06
      description: >-
        The PT-apyUSD-18JUN2026 is the asset used as collateral in a Morpho
        market with apxUSD as the loan token.
    - chainId: 1
      address: '0x3eaa0f0f0a5d3d595ae4e4b0d27f439d01c3e7b2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x9bc98c2f20ac58287ef2c860eea53a2fdc27c17a7817ff1206c0b7840cc7cd79
      description: >-
        The PT-reUSD-25JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 130
      address: '0x9d9874e867b877dd0a3f1eafb8bb1bc54eecc682'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/unichain/market/0x87a686cc100aabe917f8e1ad58140a1b63f0edbb9650a32c0526718dc610b2d5
      description: >-
        The PT-cUSD-23JUL2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x2fb3713487c7812e7309935b034f40228841666f6b048faf31fd2110ae674f20
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x5eaaebc81e9e27972ab458811d1b60828e8ab51ef6620f9b3918fd7e68eecec1
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x9db38d74a0d29380899ad354121dfb521adb0548'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x5cebfae10f5e88d33df2421923f3d9f32359429fda2f78edacc9b4fdb09b0553
      description: >-
        The PT-USDG-28MAY2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x9db38d74a0d29380899ad354121dfb521adb0548'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x16f269c5cc745b486060d42e21aef2f33edfe4b8cf6dce95e518a789469aae78
      description: >-
        The PT-USDG-28MAY2026 is the asset used as collateral in a Morpho market
        with AUSD as the loan token.
    - chainId: 1
      address: '0x3eaa0f0f0a5d3d595ae4e4b0d27f439d01c3e7b2'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x3fea56ab83b05840dc83dc6b3d2f2fbd938147cbaa8126bac529e6c820058253
      description: >-
        The PT-reUSD-25JUN2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 8453
      address: '0x25cb814c094b3ee4b19bfcab4c190c53d7890635'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/base/market/0x5c01254d8549521b43f922e175a270f0ef2e00d5c5f3f343bcd5f8451dcf93fe
      description: >-
        The PT-apxUSD-18JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x619d75e3b790ebc21c289f2805bb7177a7d732e2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x7dd7fd034b18a3cc6fccaec556e24cfa727757059f526eb87e9f26704c7a6dc2
      description: >-
        The PT-srUSDe-25JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x619d75e3b790ebc21c289f2805bb7177a7d732e2'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x1bd93f3ef76c3debad2b6023291af6a81125e71adfe775c2177afd7b79f7e41e
      description: >-
        The PT-srUSDe-25JUN2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x1d69402390657308c91179aa184bf992908c1e08'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x9464b3d42133c10c8b216d3d9429b43e98c2f3856a87940ef18b8bdd3e7bd831
      description: >-
        The PT-USDat-27AUG2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
  yt: []
  lp: []
